### ISSUE TITLE
Add instruction to install nodemon globally

### ISSUE THREAD

**Issue by thedixieflatline** [leob/feathers-next#1]
Hi.

Thanks for creating this example project!

Suggest a tweek to the documentation.

From a fresh clone you need to install nodemon globally.

npm install nodemon -g

Alternatively add as a dev dependency in package.json

  "devDependencies": {
    "eslint": "^4.6.1",
    "mocha": "^3.5.0",
    "nodemon": "^1.19.2",
    "request": "^2.81.0",
    "request-promise": "^4.2.1"
  }
}

This will help less experienced developers get going and for those like me that try to avoid global dependencies unless absolutely necessary.

**Comment by leob** [comment]
Hey man, thanks! Glad that the project is useful for you, and thanks for pointing this out. I've updated the README and included your tweaks. Let me know if this looks okay and I'll close the issue.

P.S. when I have some time I should give this repo some love, the dependencies are outdated and it would be good if I update them to the newest version (especially `feathers` and `next.js`).

**Comment by thedixieflatline** [comment]
Great work giving the full options for install of the nodemon dependency.
I think this helps people new to NPM if they come here early on in their journey
